app/models/article.py
import os
import hashlib
from itertools import groupby
from datetime import datetime

import jieba
from flask import url_for
from sqlalchemy import desc

from app import redis, logger
from config import Config
from app.utils.markdown import MD
from app.utils.convert import todatetime
from app.utils.similarity import similarity
from app.exceptions import ValidationError
from app.models import db, belong_to, User, Role, Words, WordLocation, Tag, Category


class Article(db.Model):
    __tablename__ = 'articles'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64), unique=True)  # 标题
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)

    # For markdown file
    name = db.Column(db.String(64), unique=True, index=True)  # 文件名(可能为标题)
    md5 = db.Column(db.String(32))

    # Relationship
    tags = db.relationship(
        'Tag',
        secondary=belong_to,
        backref=db.backref('articles', lazy='dynamic'),
        lazy='dynamic',
    )
    comments = db.relationship('Comment', backref='article', lazy='dynamic')
    ratings = db.relationship('Rating', backref='article', lazy='dynamic')
    wordlocations = db.relationship('WordLocation', backref='article', lazy='dynamic')

    # ForeignKey
    # backref='category'
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))
    # backref='author'
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    __mapper_args__ = {"order_by": desc(timestamp)}

    @classmethod
    def archives(cls):
        archives = groupby(
            cls.query.all(),
            key=lambda article: (article.timestamp.year, article.timestamp.month)
        )
        return archives

    @property
    def content(self):
        """整合标题、分类、标签等内容并返回，用于文章的相似性判断"""
        content = " ".join([self.body]
                           + [self.title] * 3
                           + [self.category.name] * 3
                           + [tag.name for tag in self.tags] * 3)
        return content

    @property
    def words(self):
        """对自身的markdown格式内容进行中文分词并返回结果"""
        words = [word.lower() for word in jieba.cut_for_search(self.content)]
        return words

    def _is_indexed(self):
        """如果文章已经在WordLocation中建立索引，则返回True"""
        return WordLocation.query.filter_by(article=self).first() is not None

    def _build_index(self):
        """为文章建立索引"""
        if self._is_indexed():
            return
        logger.info(f'Indexing {self.title}...')

        for loc, word_value in enumerate(self.words):
            if Words._should_ignore(word_value):
                continue
            word = Words.query.filter_by(value=word_value).first()
            if word is None:
                word = Words(value=word_value)
                db.session.add(word)
                db.session.commit()
            wordlocation = WordLocation(article=self, word=word, location=loc)
            db.session.add(wordlocation)
            db.session.commit()

    def _delete_index(self):
        """删除文章索引"""
        if self.wordlocations:
            for wordlocation in self.wordlocations:
                db.session.delete(wordlocation)
            db.session.commit()

    def _rebuild_index(self):
        """重新为文章建立索引"""
        self._delete_index()
        self._build_index()

    def _cache_similar(self):
        logger.info(f"Cache: {self.title}")
        for other in Article.query.all():
            if self == other:
                continue
            sim = similarity(self.content, other.content)
            redis.zadd(self.title, {other.title: sim})
            redis.zadd(other.title, {self.title: sim})

    def _delete_cache(self):
        logger.info(f"Delete Cache: {self.title}")
        redis.delete(self.title)
        for other in Article.query.all():
            if self == other:
                continue
            redis.zrem(other.title, self.title)

    def add_tags(self, tag_names):
        """增加文章的tags
        Args:
            tag_names: tag名称组成的list
        """
        for tag_name in tag_names:
            tag = Tag.query.filter_by(name=tag_name).first()
            if tag is None:
                tag = Tag(name=tag_name)
            db.session.add(tag)
            self.tags.append(tag)

    def delete_tags(self):
        """删除文章的所有tag"""
        for tag in self.tags.all():
            self.tags.remove(tag)
            if tag.articles is None:
                db.session.delete(tag)

    def set_category(self, category):
        """设置文章的category(如果之前不存在category则增加)
        Args:
            category: category的名称或id
        """
        if isinstance(category, int):
            new_category = Category.query.get(category)
            self.category = new_category
            return
        new_category = Category.query.filter_by(name=category).first()
        if new_category is None:
            new_category = Category(name=category)
        self.category = new_category

    def delete(self):
        """删除存在的文章记录"""
        self.delete_tags()
        self._delete_index()
        self._delete_cache()
        db.session.delete(self)
        return "[article] %s is deleted" % self.title

    def get_md5(self):
        """得到文章的md5值"""
        md5 = hashlib.md5()
        with open(self.sc_path, "rb") as scf:
            while True:
                content = scf.read(1024)
                if not content:
                    break
                md5.update(content)
        return md5.hexdigest()

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        target.body_html = MD.convert(value)
        # TODO: 为新增文章建立index
        # NOTE: 要注意文章内容改变则立即执行，
        #       而此时可能文章还没有id(要db.commit后)，
        #       并且文章的标题、目录和标签可能未改变
        # rebuild_index.delay(target)

    def to_json(self):
        """将文章信息转换为json格式"""
        article_json = {
            'url': url_for('api.get_article', id=self.id, _external=True),
            'body': self.body,
            'body_html': self.body_html,
            'timestamp': self.timestamp,
            'author_url': url_for('api.get_user', id=self.author_id),
        }
        return article_json

    @staticmethod
    def from_json(json_article):
        title = json_article.get('title')
        if title is None or title == '':
            raise ValidationError('Article does not have title')
        body = json_article.get('body')
        if body is None or body == '':
            raise ValidationError('Article does not have body')
        category = json_article.get('category', '未分类')
        tags = json_article.get('tags', ['无标签'])
        # TODO: 如果文章title(name)重复应进行提示
        article = Article(
            title=title,
            name=title,
            body=body,
        )
        article.set_category(category)
        article.add_tags(tags)
        return article

    @staticmethod
    def from_jekyll_json(json_article):
        """同步jekyll文章"""
        article_file_name = json_article.get('article_file_name')
        category_name = json_article.get('category_name')

        content = json_article.get('content')
        if content is None or content == '':
            raise ValidationError('Article does not have a body ')

        article = Article()
        article.body = content  # 必须
        article.body_html = MD.convert(content)
        title = MD.Meta.get('title')  # 必须
        if title is None or title == '':
            raise ValidationError('Article does not have title')
        article.title = title
        article.name = article.title  # 必须

        timestamp = MD.Meta.get('date')  # 优先文件头定义的date
        if timestamp:
            article.timestamp = todatetime(timestamp)
        else:  # 否则试图从文件名提取date
            article.timestamp = todatetime(article_file_name)

        tag_names = MD.Meta.get('tags', ['无标签'])

        try:
            # XXX: 查清标题冲突发生在那一步
            article.set_category(category_name)
            article.add_tags(tag_names)
            db.session.add(article)
            db.session.commit()
        except Exception:
            db.session.rollback()
            return None
        else:
            return article

    def __repr__(self):
        return '<Article %r>' % self.title

    # The following function are ready for the markdwon file
    @property
    def md_name(self):
        return self.name + '.md'

    @property
    def sc_path(self):
        return os.path.join(Config.ARTICLES_SOURCE_DIR, self.md_name)

    def md_is_change(self):
        old_md5 = self.md5
        now_md5 = self.get_md5()
        return old_md5 != now_md5

    def md_relog(self):
        """对`/articles`目录中已经记录的文章，重新记录文章中各属性"""
        with open(self.sc_path, "r", encoding="utf-8") as scfd:
            self.body = scfd.read()

        self.body_html = MD.convert(self.body)
        title = MD.Meta.get('title')  # 必须
        if title is None or title == '':
            raise ValidationError('Article does not have title')
        self.title = title

        timestamp = MD.Meta.get('date')
        if timestamp:
            self.timestamp = todatetime(timestamp)
        else:  # 否则试图从文件名提取date
            self.timestamp = todatetime(self.name)

        self.md5 = self.get_md5()

        admin_role = Role.query.filter_by(name='Administrator').first()
        self.author = User.query.filter_by(role=admin_role).first()

        category_name = MD.Meta.get('category', '未分类')
        tag_names = MD.Meta.get('tags', ['无标签'])

        try:
            self.set_category(category_name)
            self.delete_tags()
            self.add_tags(tag_names)
            db.session.add(self)
            db.session.commit()
        except Exception:
            db.session.rollback()
            return None
        else:
            return self

    @classmethod
    def md_render(cls, name):
        """根据markdown文件生成文章记录，更新记录中各属性
        Args:
            name: 文件名(去除后缀)
        """

app/article/forms.py
from flask_wtf import FlaskForm
from wtforms import ValidationError
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import Required, Length
from flask_pagedown.fields import PageDownField

from app.models import Category, Article


class EditArticleForm(FlaskForm):
    title = StringField('题目', validators=[Required(), Length(1, 64)])
    category = SelectField('分类', coerce=int)
    tags = StringField('标签', validators=[Length(0, 64)])
    body = PageDownField("文章内容", validators=[Required()])
    submit = SubmitField('提交')

    def __init__(self, *args, **kwargs):
        super(EditArticleForm, self).__init__(*args, **kwargs)
        self.category.choices = [
            (category.id, category.name)
            for category in Category.query.order_by(Category.name).all()
        ]

    def validate_title(self, field):
        if (Article.query.filter_by(name=field.data).first()
                or Article.query.filter_by(title=field.data).first()):
            raise ValidationError('文章标题已被使用')


class ModifyArticleForm(FlaskForm):
    title = StringField('题目', validators=[Required(), Length(1, 64)])
    category = SelectField('分类', coerce=int)
    tags = StringField('标签', validators=[Length(0, 64)])
    body = PageDownField("文章内容", validators=[Required()])
    submit = SubmitField('提交')

    def __init__(self, *args, **kwargs):
        super(ModifyArticleForm, self).__init__(*args, **kwargs)
        self.category.choices = [
            (category.id, category.name)
            for category in Category.query.order_by(Category.name).all()
        ]

app/article/__init__.py
from flask import Blueprint

article = Blueprint('article', __name__)

from . import views

app/article/views.py
from flask import flash, render_template, redirect, url_for, request, abort
from flask_login import current_user, login_required


from app import db, redis
from app.models import Article, Comment, Permission, Rating
from app.decorators import permission_required, author_required
from app.article import article as article_blueprint
from app.article.forms import EditArticleForm, ModifyArticleForm
from app.tasks import build_index, rebuild_index


@article_blueprint.route('/<title>', methods=['GET'])
def article(title):
    """ 显示单篇文章 """
    article = Article.query.filter_by(title=title).first_or_404()

    # 相似文章
    sim_articles = redis.zrevrange(article.title, 0, 4, withscores=True)

    # 获取评分情况
    ratings = article.ratings.all()
    num_rating = len(ratings)
    try:
        avg_rating = sum(map(lambda rating: rating.value, ratings)) / num_rating
    except ZeroDivisionError:
        avg_rating = None

    try:
        current_user_rating = article.ratings.filter_by(user=current_user).first().value
    except AttributeError:
        current_user_rating = None

    try:
        current_user_id = current_user.id
    except AttributeError:
        current_user_id = None

    return render_template('article/article.html', article=article,
                           sim_articles=sim_articles,
                           num_rating=num_rating, avg_rating=avg_rating,
                           current_user_rating=current_user_rating,
                           article_id=article.id, user_id=current_user_id)


@article_blueprint.route('/edit', methods=['GET', 'POST'])
@author_required
def edit():
    form = EditArticleForm()
    if form.validate_on_submit():
        article = Article(
            title=form.title.data,
            # TODO: delete
            name=form.title.data,
            body=form.body.data,
            author=current_user._get_current_object()
        )
        article.set_category(form.category.data)
        article.add_tags(form.tags.data.strip().split(' '))
        db.session.add(article)
        db.session.commit()
        build_index.delay(article.id)
        return redirect(url_for('article.article', title=article.title))
    return render_template('article/edit.html', form=form)


@article_blueprint.route('/delete/<title>')
@author_required
def delete(title):
    article = Article.query.filter_by(title=title).first_or_404()
    if current_user != article.author \
            and not current_user.can(Permission.ADMINISTER):
        abort(403)
    else:
        flash(article.delete())
        return (redirect(request.args.get('next')
                or url_for('user.user', username=current_user.username)))


@article_blueprint.route('/modify/<title>', methods=['GET', 'POST'])
@author_required
def modify(title):
    article = Article.query.filter_by(title=title).first_or_404()
    form = ModifyArticleForm(article=article)
    if current_user != article.author \
            and not current_user.can(Permission.ADMINISTER):
        abort(403)
    if form.validate_on_submit():
        article.title = form.title.data
        # TODO: delete
        if article.name is None:
            article.name = form.title.data
        article.body = form.body.data

        article.set_category(form.category.data)

        article.delete_tags()
        article.add_tags(form.tags.data.split(' '))

        db.session.add(article)
        db.session.commit()

        rebuild_index.delay(article.id)

        flash('您的文章已经成功修改')
        return redirect(url_for('article.article', title=article.title))
    form.title.data = article.title
    form.category.data = article.category.id
    form.tags.data = " ".join(tag.name for tag in article.tags)
    form.body.data = article.body
    return render_template('article/edit.html', form=form)


@article_blueprint.route('/rating', methods=['POST'])
@login_required
def rating():
    user_id = request.json['user_id']
    rating_value = request.json['rating_value']
    article_id = request.json['article_id']
    rating = Rating.query.filter_by(user_id=user_id, article_id=article_id).first()
    if rating is None:  # 新建
        rating = Rating(value=rating_value, user_id=user_id, article_id=article_id)
    else:  # 更改
        rating.value = rating_value
    db.session.add(rating)
    return "Rating done."


@article_blueprint.route('/comment', methods=['POST'])
@login_required
def comment():
    user_id = request.form['user_id']
    article_id = request.form['article_id']
    comment_body = request.form['comment_body']
    comment = Comment(body=comment_body, article_id=article_id, author_id=user_id)
    db.session.add(comment)
    flash("你的评论已提交")
    return redirect(request.args.get('next') or url_for('main.index'))


@article_blueprint.route('/moderate/<comment_id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.article.author == current_user\
            or comment.author == current_user\
            or current_user.is_administrator:
        db.session.delete(comment)
        flash('评论已经删除')
    return redirect(url_for('article.article', title=comment.article.title))

app/templates/article/article.html
{% extends "_layouts/default.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block head %}
{{ super() }}
<link href="{{ url_for('static', filename='styles/article.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='styles/syntax.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='styles/rating.css') }}" rel="stylesheet">
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML">
</script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-8">
    <div class="blog-post">
      <div class="blog-post-info">
        <div class="column">
          <h2 class="blog-post-title">
            <a href="{{ url_for('article.article', title=article.title) }}">{{article.title}}</a>
          </h2>
          <p class="blog-post-date">{{ article.timestamp.strftime('%Y %m %d') }}</p>
        </div>
        <div class="column">
          {% for tag in article.tags %}
            <a href="/tags">
              <span class="label label-primary">Tag: {{ tag.name }}</span>
            </a>
          {% endfor %}
          <a href="/categories">
            <span class="label label-default">Category: {{ article.category.name }}</span>
          </a>
        </div>
      </div><!-- /.blog-post-info -->
      <div class="blog-post-content">
        {{ article.body_html|safe }}
      </div>
    </div><!-- /.blog-post -->

    <div class="blog-rating" data-user-id={{user_id}} data-article-id={{article_id}} data-avg-rating={{avg_rating}} data-current-rating={{current_user_rating}}>
      <div class="avg">
        {% if num_rating %}
          <p><span id="avg-rating"></span>({{ num_rating }}人已评分，平均{{ "%f" % avg_rating }}分)</p>
        {% else %}
          <p>无人评分</p>
        {% endif %}
      </div>
      <div style="display: inline-block;">
      {% if current_user.is_authenticated %}
        {% include '_includes/rating.html' %}<p>(你的评分为：<span id="current-rating">{{ current_user_rating }}</span>)</p>
      {% else %}
        <a href="{{ url_for('auth.login', next='/article/'+article.name) }}">评分前请先登录</a>
      {% endif %}
      </div>
    </div>

    <div id="comment-box" data-user-id={{user_id}} data-article-id={{article_id}} user-is-authenticated={{current_user.is_authenticated}}></div>

    <div class="comment">
      <div class="comment-form">
      {% if current_user.is_authenticated %}
        <p>请输入评论</p>
        <form action="{{ url_for('article.comment', next='/article/'+article.title) }}" method="post" class="form" role="form">
          <input name="user_id" type="hidden" value="{{user_id}}">
          <input name="article_id" type="hidden" value="{{article_id}}">
          <div class="form-group  required"><label class="control-label" for="body"></label>
            <input class="form-control" id="body" name="comment_body" required="" type="text" value="">
          </div>
          <input class="btn btn-default" id="submit" name="submit" type="submit" value="提交评论">
        </form>
      {% else %}
        <a href="{{ url_for('auth.login', next='/article/'+article.name) }}">评论前请先登录</a>
      {% endif %}
      </div>

      <ul class="comments">
      {% for comment in article.comments %}
        <li class="comment">
          <div class="comment-date">{{ comment.timestamp }}</div>
          <div class="comment-author">{{ comment.author.username }}</div>
          {% if current_user.is_authenticated
                and (current_user.is_administrator
                     or comment.author == current_user
                     or comment.article.author == current_user) %}
          <div class="moderate">
            <a href="{{ url_for('article.moderate', comment_id=comment.id) }}">
              <span class="label label-danger">Delete</span>
            </a>
          </div>
          {% endif %}
          <div class="comment-body">
              {% if comment.body_html %}
                  {{ comment.body_html | safe }}
              {% else %}
                  {{ comment.body }}
              {% endif %}
          </div>
        </li>
      {% endfor %}
      </ul>
    </div>
  </div>

  <div class="col-sm-3 col-sm-offset-1">
    <div class="blog-post-tip">
      <div id="similarity">
        <span class="label label-success">相似文章</span>
        <ul class="list-group">
        {% for title, similarity in sim_articles %}
          <li class="list-group-item">
            <a href="{{ url_for('article.article', title=title) }}">{{title}}</a>
          </li>
        {% endfor %}
        </ul>
      </div>

      <div id="similar-articles" data-article-id="{{article_id}}"></div>

      <div id="toc"></div>

      <button type="button" class="btn btn-info btn-sm" id="back-to-top">
        <span clas="glyphicon glyphicon-hand-up" aria-hidden="true"></span> 回到顶部
      </button>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
{{ super() }}
<script src="{{ url_for('static', filename='scripts/article.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/rating.js') }}"></script>
<!--
<script src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/2.0.1/remarkable.min.js"></script>
-->
<!--
<script type="module" src="{{ url_for('static', filename='scripts/comment.js') }}"></script>
-->
<!--
<script type="module" src="{{ url_for('static', filename='scripts/similarity.js') }}"></script>
-->
{% endblock %}

app/templates/article/edit.html
{% extends "_layouts/default.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Edit Article{% endblock %}

{% block head %}
{{ super() }}
<style>
/* 动态为footer添加类fixed-bottom */
.fixed-bottom {
  position: static;
}
</style>
 {% endblock %} 

{% block header %}
<div class="page-header container">
  <h1>发布文章</h1>
</div>
{% endblock %}

{% block content %}
{{ wtf.quick_form(form) }}
{% endblock %}

{% block js %}
{{ super() }}
{{ pagedown.include_pagedown() }}
<script src="{{ url_for('static', filename='scripts/edit.js') }}"></script>
{% endblock %}